// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCore.Models;

public partial class address_status
{
    [Key]
    public int status_id { get; set; }

    [Column("address_status")]
    [StringLength(30)]
    public string address_status1 { get; set; }
    //[InverseProperty("address_status")]
    public ICollection<customer_address>? customer_adress { get; set; }
}