// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCore.Models;

public partial class author
{
    [Key]
    public int author_id { get; set; }

    [StringLength(400)]
    public string author_name { get; set; }

    //[ForeignKey("author_id")]
    //[InverseProperty("author")]
    public virtual ICollection<book_author>? book_author { get; set; }
}