// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCore.Models;

public partial class book_language
{
    [Key]
    public int language_id { get; set; }

    [StringLength(8)]
    public string language_code { get; set; }

    [StringLength(50)]
    public string language_name { get; set; }

    [InverseProperty("language")]
    public virtual ICollection<book> book { get; set; } = new List<book>();
}