// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCore.Models;

public partial class book
{
    [Key]
    public int book_id { get; set; }

    public ICollection<book_author>? book_author { get; set; }

    [StringLength(400)]
    public string title { get; set; }

    [StringLength(13)]
    public string isbn13 { get; set; }

    public int? language_id { get; set; }

    public int? num_pages { get; set; }

    public DateOnly? publication_date { get; set; }

    public int? publisher_id { get; set; }

    [ForeignKey("language_id")]
    [InverseProperty("book")]
    public virtual book_language language { get; set; }

    [InverseProperty("book")]
    public virtual ICollection<order_line> order_line { get; set; } = new List<order_line>();

    [ForeignKey("publisher_id")]
    [InverseProperty("book")]
    public virtual publisher publisher { get; set; }
}