// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCore.Models;

public partial class country
{
    [Key]
    public int country_id { get; set; }

    [StringLength(200)]
    public string country_name { get; set; }

    [InverseProperty("country")]
    public virtual ICollection<address> address { get; set; } = new List<address>();
}