// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCore.Models;

[PrimaryKey("customer_id", "address_id")]
public partial class customer_address
{
    [Key]
    public int customer_id { get; set; }

    [Key]
    public int address_id { get; set; }

    [ForeignKey("status")]
    public int status_id { get; set; }
    //[InverseProperty("customer_address")]
    public address_status status { get; set; }

    [ForeignKey("address_id")]
    [InverseProperty("customer_address")]
    public virtual address address { get; set; }

    [ForeignKey("customer_id")]
    [InverseProperty("customer_address")]
    public virtual customer customer { get; set; }
}