// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCore.Models;

public partial class cust_order
{
    [Key]
    public int order_id { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? order_date { get; set; }

    public int? customer_id { get; set; }

    public int? shipping_method_id { get; set; }

    public int? dest_address_id { get; set; }

    [ForeignKey("customer_id")]
    [InverseProperty("cust_order")]
    public virtual customer customer { get; set; }

    [ForeignKey("dest_address_id")]
    [InverseProperty("cust_order")]
    public virtual address dest_address { get; set; }

    [InverseProperty("order")]
    public virtual ICollection<order_history> order_history { get; set; } = new List<order_history>();

    [InverseProperty("order")]
    public virtual ICollection<order_line> order_line { get; set; } = new List<order_line>();

    [ForeignKey("shipping_method_id")]
    [InverseProperty("cust_order")]
    public virtual shipping_method shipping_method { get; set; }
}