// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCore.Models;

public partial class order_line
{
    [Key]
    public int line_id { get; set; }

    public int? order_id { get; set; }

    public int? book_id { get; set; }

    [Precision(5, 2)]
    public decimal? price { get; set; }

    [ForeignKey("book_id")]
    [InverseProperty("order_line")]
    public virtual book book { get; set; }

    [ForeignKey("order_id")]
    [InverseProperty("order_line")]
    public virtual cust_order order { get; set; }
}